# Generated by Django 5.0.6 on 2024-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('VENDOR', 'Restaurant'), ('CUSTOMER', 'Customer')], null=True),
        ),
    ]
